name: 镜像构建检查

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g., 2025.05.5)'
        required: true
        default: '2025.05.5'


jobs:
  check-image:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: 检查镜像是否存在
        id: check
        run: |
          # 检查 GHCR 上是否存在该 tag 的镜像
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/iHost-Open-Source-Project/packages/container/armv7-hassio-supervisor/versions" |
            jq -e --arg TAG "${{inputs.tag}}" '.[] | select(.metadata.container.tags[]? == $TAG)' > /dev/null 2>&1
          echo "tag=${{inputs.tag}}"
          if [ $? -eq 0 ]; then
            echo "镜像已存在，无需构建"
            echo "should_build=false" >> $GITHUB_ENV
          else
            echo "镜像不存在，需要构建"
            echo "should_build=true" >> $GITHUB_ENV
          fi
          
      - name: 设置输出
        run: |
          echo "should_build=${{ env.should_build }}" >> $GITHUB_OUTPUT
